### ISSUE TITLE
LIBRERÍA DLL

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Valentiin01#2]
[PRACTICA DLL_Genaro Santiago Valentin.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Valentiin01/files/6769675/PRACTICA.DLL_Genaro.Santiago.Valentin.pdf)

**Comment by MLR062998** [comment]
calificación:  20/20

**Comment by josealfredo79** [comment]
Esta practica no puede tener el máximo valor si entrego casi al final del semestre

**Comment by josealfredo79** [comment]
16
